FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# ReIssue

# Group ユーザー

## ユーザー [/api/user/]

### TOPページからTwitter認証後の初期ユーザー登録API [POST]

- enteredYear: 入学年度
- name: 名前
- course: コース Media MI CS

リクエストが正常だった場合，その科とコースのデフォルトの時間割が飛んでくる

- Request (application/json)

        {
            "enteredYear": 2015,
            "name": "nersonu",
            "course": "MI"
        }
        
- Response 200 (applicaton/json)

        {
            "_id": "58c9e58fc9281e61f9a3ca1a",
            "name": "Media",
            "Mon": ["微積分", "線形代数", null, null, null, null, null],
            "Tue": [null, null, "基礎プロ", null, null, null, null],
            "Wed": [null, null, "ソフトウェア工学", null, null, null, null],
            "Thu": [null, null, null, null, null, "計算機工学", null],
            "Fri": [null, "プログラミング言語論", null, "統計学", null, null, null],
            "Sat": [null, null, null, null, null, null, null]
        }


## ユーザー [/api/user/{?_id}]

### ユーザーが履修している科目を登録するAPI[POST]

- Request (applicaiton/json)

        {
            "user_id": "58b5179a82e96efabf76866f",
            "taking": {
                "Mon": ["微積分", "線形代数", null, null, null, null, null],
                "Tue": [null, null, "基礎プロ", null, null, null, null],
                "Wed": [null, null, "ソフトウェア工学", null, null, null, null],
                "Thu": [null, null, null, null, null, "計算機工学", null],
                "Fri": [null, "プログラミング言語論", null, "統計学", null, null, null],
                "Sat": [null, null, null, null, null, null, null]
                }
        }
        
- Response 200 (application/json)



### チャット画面の左側の情報API [GET]

- 空きコマはnullとして表現される'
- 後ろのパラメータにユーザーの_idの文字列をつけないといけない

- Request
    
- Parameters:
    - _id: 58b5179a82e96efabf76866f (string, required) - ユーザのユニークID
    
- Response 200 (application/json)

        {
            "_id": "58b5179a82e96efabf76866f",
            "name": "テスト太郎",
            "taking": {
                "Mon": ["微積分", "線形代数", null, null, null, null, null],
                "Tue": [null, null, "基礎プロ", null, null, null, null],
                "Wed": [null, null, "ソフトウェア工学", null, null, null, null],
                "Thu": [null, null, null, null, null, "計算機工学", null],
                "Fri": [null, "プログラミング言語論", null, "統計学", null, null, null],
                "Sat": [null, null, null, null, null, null, null]
                }
        }

# Group 科目
## 科目 [/api/subject/]

### 全科目返す [GET]

- Request

- Response 200 (application/json)

        [
            {
                "_id":"58d0dea52c0663e94d47e1a6",
                "name":"グラフとネットワーク",
                "dayOfWeek":"Mon",
                "period":2,
                "course":["CS","MI"]
            },
            {
                "_id":"58d0dea52c0663e94d47e1a7",
                "name":"情報数理工学実験第一",
                "dayOfWeek":"Mon",
                "period":3,"course":["MI"]
            }
        ]


## 特定のコースのデフォルト時間割を返す [/api/subject/getByCourse/?{course}]

### 特定のコースの科目だけ返す [GET]

- Request

    - Header

            Authorization: $ACCESS_TOKEN

- Parameters
    - course: MI(string, required) - Media, MI, CS に対応

- Response 200 (application/json)

        {
            "Fri": [
                null, 
                null, 
                {
                    "_id": "58d0dea72c0663e94d47e1b6", 
                    "name": "ヒューマンインタフェース"
                }, 
                {
                    "_id": "58d0dea72c0663e94d47e1b7", 
                    "name": "オートマトン理論"
                }, 
                null, 
                null, 
                null
            ], 
            "Mon": [
                null, 
                {
                    "_id": "58d0dea52c0663e94d47e1a6", 
                    "name": "グラフとネットワーク"
                }, 
                {
                    "_id": "58d0dea52c0663e94d47e1a7", 
                    "name": "情報数理工学実験第一"
                }, 
                {
                    "_id": "58d0dea52c0663e94d47e1a8", 
                    "name": "情報数理工学実験第一"
                }, 
                null, 
                null, 
                null
            ], 
            "Thu": [
                null, 
                {
                    "_id": "58d0dea72c0663e94d47e1b3", 
                    "name": "プログラム言語論"
                }, 
                {
                    "_id": "58d0dea72c0663e94d47e1b4", 
                    "name": "アルゴリズム論第一"
                }, 
                {
                    "_id": "58d0dea72c0663e94d47e1b5", 
                    "name": "Technical English"
                }, 
                null, 
                null, 
                null
            ], 
            "Tue": [
                null, 
                {
                    "_id": "58d0dea62c0663e94d47e1ab", 
                    "name": "数値解析"
                }, 
                {
                    "_id": "58d0dea62c0663e94d47e1ac", 
                    "name": "論理設計学"
                }, 
                {
                    "_id": "58d0dea62c0663e94d47e1ad", 
                    "name": "データベース論"
                }, 
                null, 
                null, 
                null
            ], 
            "Wed": [
                null, 
                {
                    "_id": "58d0dea62c0663e94d47e1ae", 
                    "name": "言語処理系論"
                }, 
                {
                    "_id": "58d0dea62c0663e94d47e1af", 
                    "name": "情報数理工学実験第一"
                }, 
                {
                    "_id": "58d0dea62c0663e94d47e1b0", 
                    "name": "情報数理工学実験第一"
                }, 
                null, 
                null, 
                null
            ]
        }

## m曜日n限な科目を全て返す [/api/subject/getByDayAndPeriod/{?period,dayOfWeek}]

### m曜日n限な科目を全て返す [GET]

- Request

    - Header

            Authorization: $ACCESS_TOKEN

- Parameters
    - period: 2(Number, required) - 1~7
    - dayOfWeek: Tue(string, required) - Mon, Tue, Wed, Thu, Fri, Sat

- Response 200 (application/json)

        [
            {
                "_id": "58d0dea62c0663e94d47e1ab", 
                "name": "数値解析"
            }, 
            {
                "_id": "58d0dedd2c0663e94d47e1bd", 
                "name": "プログラミング言語実験"
            }
        ]

# Group チャット

## チャットログ [/api/chatlog/{subjectId}]

### 科目でチャットログ取得 [GET]

- Request

- Parameters 
    - subjectId: 58b552de14d5f1260bed8574 (string, required) - 科目ID
    
- Response 200 (application/json)

        [
          {
            "_id": "58d0b14a3801831981ce5bf1",
            "subject": "58b552de14d5f1260bed8574",
            "speaker": "111111111111111111111111",
            "text": "必修落とした😭",
            "__v": 0,
            "created": "2017-03-21T04:51:22.903Z"
          },
          {
            "_id": "58d0b1503801831981ce5bf2",
            "subject": "58b552de14d5f1260bed8574",
            "speaker": "111111111111111111111111",
            "text": "うぇーい",
            "__v": 0,
            "created": "2017-03-21T04:51:28.453Z"
          }
        ]