FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# ReIssue

# Group ユーザー

## ユーザー [/api/user/]

### TOPページからTwitter認証後の初期ユーザー登録API [POST]

- enteredYear: 入学年度
- name: 名前
- course: "J" "I" "M" "S", "K",  "1", "2", "3", "KN"
- optionalCourse: 最大4つまで，一つ目の要素は1年時のクラス，二つ目の要素は2年時のクラス，三つ目以降の要素は専攻コース

リクエストが正常だった場合，その科とコースのデフォルトの時間割が飛んでくる

- Request (application/json)

        {
            "enteredYear": 2015,
            "name": "nersonu",
            "course": "I",
            "optionalCource": [3, 1, 3]
        }
        
- Response 200 (applicaton/json)

        {
            "_id": "58c9e58fc9281e61f9a3ca1a",
            "name": "I3",
            "Mon": ["微積分", "線形代数", null, null, null, null, null],
            "Tue": [null, null, "基礎プロ", null, null, null, null],
            "Wed": [null, null, "ソフトウェア工学", null, null, null, null],
            "Thu": [null, null, null, null, null, "計算機工学", null],
            "Fri": [null, "プログラミング言語論", null, "統計学", null, null, null],
            "Sat": [null, null, null, null, null, null, null]
        }


## ユーザー [/api/user/{?_id}]

### チャット画面の左側の情報API [GET]

- 空きコマはnullとして表現される'
- 後ろのパラメータにユーザーの_idの文字列をつけないといけない

- Request
    
- Parameters:
    - _id: 58b5179a82e96efabf76866f (string, required) - ユーザのユニークID
    
- Response 200 (application/json)

        {
            "_id": "58b5179a82e96efabf76866f",
            "name": "テスト太郎",
            "taking": {
                "Mon": ["微積分", "線形代数", null, null, null, null, null],
                "Tue": [null, null, "基礎プロ", null, null, null, null],
                "Wed": [null, null, "ソフトウェア工学", null, null, null, null],
                "Thu": [null, null, null, null, null, "計算機工学", null],
                "Fri": [null, "プログラミング言語論", null, "統計学", null, null, null],
                "Sat": [null, null, null, null, null, null, null]
                }
        }